uploadcare/blocks

- upload-blocks/EditableCanvas/EditableCanvas.js
- upload-blocks/FileItem/FileItem.js
- upload-blocks/UploadDetails/UploadDetails.js
- upload-blocks/svg-backgrounds/svg-backgrounds.js
Previews for external urls are disabled
> feat(upload-details): show non-image previews

- build-libs.js
About `@license` - https://jsdoc.app/tags-license.html
Example of banner:
```js
/**
* @license
* MIT License
* 
* Copyright (c) 2021 Uploadcare (hello@uploadcare.com). All rights reserved.
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
* 
* THE SOFTWARE IS …
```
> chore: add license banner to the js bundle

- CHANGELOG.md
- lerna.json
- live-html/package.json
- upload-blocks/package.json
- uploader/package.json
> Revert "chore: release v0.0.3-alpha.2"

- README.md
- uploader/README.md
> Grammar fixes for uploader&JSDK readme

- README.md
- uploader/README.md
> fix-supported-browsers

- upload-blocks/FileItem/FileItem.js
> fix: external source filename passing

- upload-blocks/doc_assets/basic-demo.snpt.html
- uploader/README.md
https://github.com/uploadcare/jsdk/issues/100
> fix: css URLs in docs (issue #100)

- abstract/Block.js
- assets/js/app-shell.js
- blocks/CameraSource/CameraSource.js
- blocks/ExternalSource/ExternalSource.js
- blocks/SimpleBtn/SimpleBtn.js
- blocks/SimpleBtn/simple-btn.css
- blocks/SourceBtn/SourceBtn.js
- blocks/UploadList/UploadList.js
- blocks/UrlSource/UrlSource.js
- blocks/themes/uc-basic/config.css
- solutions/cloud-image-editor/index.html
- solutions/cloud-image-editor/index.js
> Single source

- .eslintrc
- assets/js/app-shell.js
- blocks/CloudImageEditor/index.js
- blocks/CloudImageEditor/src/elements/button/test.js
- blocks/CloudImageEditor/src/elements/slider/test.html
- blocks/CloudImageEditor/src/elements/slider/test.js
- package-lock.json
- package.json
- solutions/cloud-image-editor/CloudEditor.js
- solutions/cloud-image-editor/index.js
- solutions/file-uploader/minimal/FileUploaderMinimal.js
- solutions/file-uploader/regular/FileUploaderRegular.js
We have some circular and duplicated imports/exports at the root `index.js`
Fix it and setup eslint to detect such problems in future.
> chore: setup import lint

- TOC.md
- blocks/CameraSource/camera-source.css
- blocks/CloudImageEditor/index.css
- blocks/ExternalSource/external-source.css
- blocks/Modal/modal.css
- blocks/Tabs/tabs.css
- blocks/UploadDetails/upload-details.css
- blocks/test/raw.html
- build-items.js
- package-lock.json
- solutions/README.md
- solutions/file-uploader/README.md
- solutions/file-uploader/inline/FileUploaderInline.js
- solutions/file-uploader/inline/README.md
- solutions/file-uploader/inline/demo.snippet.htm
- solutions/file-uploader/inline/index.css
- solutions/file-uploader/inline/index.html
> Uploader inline mode

- solutions/adaptive-image/README.md
> Grammar fixes

- submodules/README.md
> Grammar fix

- README.md
- solutions/adaptive-image/README.md
- solutions/file-uploader/README.md
Fix web component description according to the changes in Lab documentation.
> Fix wording in titles and descriptions

- abstract/Block.js
- assets/htm/upload-blocks-demo.htm
- blocks/DataOutput/DataOutput.js
- blocks/DropArea/DropArea.js
- blocks/FileItem/FileItem.js
- blocks/Img/ImgBase.js
- blocks/Img/props-map.js
- blocks/MessageBox/MessageBox.js
- blocks/UploadList/UploadList.js
- blocks/themes/lr-basic/l10n.css
- package-lock.json
- package.json
- solutions/file-uploader/inline/FileUploaderInline.js
- solutions/file-uploader/inline/demo.htm
- solutions/file-uploader/minimal/FileUploaderMinimal.js
- solutions/file-uploader/minimal/demo.htm
- solutions/file-uploader/regular/FileUploaderRegular.js
- solutions/file-uploader/regular/demo.htm
- static-gen/importmap.json
> Integration issues

- abstract/ActivityBlock.js
- abstract/UploaderBlock.js
- blocks/StartFrom/StartFrom.js
Fixes https://github.com/uploadcare/blocks/issues/339
> fix: single source behaviour

- blocks/CloudImageEditor/ref.htm
> fix(docs): set cloud-editor examples body height

- abstract/Block.js
- abstract/UploaderBlock.js
- blocks/Copyright/Copyright.js
- blocks/FileItem/FileItem.js
- blocks/FileItem/file-item.css
- blocks/SimpleBtn/simple-btn.css
- blocks/themes/lr-basic/config.css
- get-started/configuration/README.md
- solutions/file-uploader/README.md
- types/tags.d.ts
> Features needed for uploader configurator

- build-ssr-stubs.js
- index.js
- index.ssr.js
- package-lock.json
- package.json
- tsconfig.json
> fix: stub package exports for SSR

- package.json
> chore: add default exports

- .github/workflows/shipjs-trigger.yml
> chore: fix ci github user

- types/jsx.d.ts
> fix(jsx): add missing lr-file-uploader-inline tag

- blocks/Modal/Modal.js
> fix(modal): restore scroll lock on modal destroy

- solutions/file-uploader/inline/FileUploaderInline.js
> fix(file-uploader-inline): do not try to hide drop area because it hides itself

- package.json
> fix(package.json): add types to exports field

- blocks/ProgressBarCommon/progress-bar-common.css
> fix(progress-bar-common): ignore pointer events when not active

- blocks/CloudImageEditor/src/CloudEditor.js
- blocks/CloudImageEditor/src/css/common.css
- blocks/CloudImageEditor/src/css/icons.css
- build-items.js
> fix(cloud-editor): solution bundle

- index-browser.js
> fix: add empty export to the blocks-browser bundle to fix working under isolatedModules

- blocks/ExternalSource/ExternalSource.js
- blocks/themes/lr-basic/config.css
> feature(external-source): configurable social base url

- blocks/CloudImageEditor/src/CloudEditor.js
- blocks/CloudImageEditor/src/css/common.css
- blocks/CloudImageEditor/src/css/icons.css
> fix: do not use host-context unsupported in firefox and safari

- blocks/CloudImageEditor/src/CloudEditor.js
> fix(cloud-editor): double init

- utils/fileTypes.js
- utils/fileTypes.test.js
> fix: make file extension validation case-insensitive

- solutions/cloud-image-editor/CloudImageEditor.js
> fix(cloud-image-editor): fix `initEditor` type

- solutions/file-uploader/minimal/index.js
> fix(minimal): add exports of `lr-config` and `upload-ctx-provider`
